sonar:
  stage: test
  image: maven:3-jdk-11-slim
  script: "mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent verify sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=tibhannover -Dsonar.login=${SONAR_LOGIN}"