insert into user (name, password, id) values ('admin', '$2a$10$VurnNhud5afA1jRh0JQm2ebjBYN2RfO1OfQSXwdlw9YFGxbghvGYm', -1) // pw admin
insert into user_role (user_id, role_id) values (-1, 'MANAGE_USERS')
insert into user_role (user_id, role_id) values (-1, 'PROCESS_DOCUMENTS')
insert into user_role (user_id, role_id) values (-1, 'IMPORT_DOCUMENTS')

insert into import_filter (id, condition_type, condition, action) values (-1, 'FORM_KEYWORD', '.*Jugendbuch.*', 'IGNORE')
insert into import_filter (id, condition_type, condition, action) values (-2, 'FORM_KEYWORD', '.*Jugendliteratur.*', 'IGNORE')
insert into import_filter (id, condition_type, condition, action) values (-3, 'FORM_KEYWORD', '.*juvenile literature.*', 'IGNORE')
insert into import_filter (id, condition_type, condition, action) values (-4, 'FORM_KEYWORD', '.*Reiseführer.*', 'IGNORE')

insert into category (type, category, description, id) values ('DDC', '000', 'Allgemeines, Wissenschaft', -1)
insert into category (type, category, description, id) values ('DDC', '004', 'Informatik', -2)
insert into category (type, category, description, id) values ('DDC', '010', 'Bibliografien', -3)
insert into category (type, category, description, id) values ('DDC', '020', 'Bibliotheks- und Informationswissenschaft', -4)
insert into category (type, category, description, id) values ('DDC', '030', 'Enzyklopädien', -5)
insert into category (type, category, description, id) values ('DDC', '050', 'Zeitschriften, fortlaufende Sammelwerke', -6)
insert into category (type, category, description, id) values ('DDC', '060', 'Organisationen, Museumswissenschaft', -7)
insert into category (type, category, description, id) values ('DDC', '070', 'Nachrichtenmedien, Journalismus, Verlagswesen', -8)
insert into category (type, category, description, id) values ('DDC', '080', 'Allgemeine Sammelwerke', -9)
insert into category (type, category, description, id) values ('DDC', '090', 'Handschriften, seltene Bücher', -10)
insert into category (type, category, description, id) values ('DDC', '100', 'Philosophie', -11)
insert into category (type, category, description, id) values ('DDC', '130', 'Parapsychologie, Okkultismus', -12)
insert into category (type, category, description, id) values ('DDC', '150', 'Psychologie', -13)
insert into category (type, category, description, id) values ('DDC', '200', 'Religion, Religionsphilosophie', -14)
insert into category (type, category, description, id) values ('DDC', '220', 'Bibel', -15)
insert into category (type, category, description, id) values ('DDC', '230', 'Theologie, Christentum', -16)
insert into category (type, category, description, id) values ('DDC', '290', 'Andere Religionen', -17)
insert into category (type, category, description, id) values ('DDC', '300', 'Sozialwissenschaften, Soziologie, Anthropologie', -18)
insert into category (type, category, description, id) values ('DDC', '310', 'Allgemeine Statistiken', -19)
insert into category (type, category, description, id) values ('DDC', '320', 'Politik', -20)
insert into category (type, category, description, id) values ('DDC', '330', 'Wirtschaft', -21)
insert into category (type, category, description, id) values ('DDC', '333.7', 'Natürliche Ressourcen, Energie und Umwelt', -22)
insert into category (type, category, description, id) values ('DDC', '340', 'Recht', -23)
insert into category (type, category, description, id) values ('DDC', '355', 'Militär', -24)
insert into category (type, category, description, id) values ('DDC', '360', 'Soziale Probleme, Sozialdienste, Versicherungen', -25)
insert into category (type, category, description, id) values ('DDC', '370', 'Erziehung, Schul- und Bildungswesen', -26)
insert into category (type, category, description, id) values ('DDC', '380', 'Handel, Kommunikation, Verkehr', -27)
insert into category (type, category, description, id) values ('DDC', '390', 'Bräuche, Etikette, Folklore', -28)
insert into category (type, category, description, id) values ('DDC', '400', 'Sprache, Linguistik', -29)
insert into category (type, category, description, id) values ('DDC', '420', 'Englisch', -30)
insert into category (type, category, description, id) values ('DDC', '430', 'Deutsch', -31)
insert into category (type, category, description, id) values ('DDC', '439', 'Andere germanische Sprachen', -32)
insert into category (type, category, description, id) values ('DDC', '440', 'Französisch, romanische Sprachen allgemein', -33)
insert into category (type, category, description, id) values ('DDC', '450', 'Italienisch, Rumänisch, Rätoromanisch', -34)
insert into category (type, category, description, id) values ('DDC', '460', 'Spanisch, Portugiesisch', -35)
insert into category (type, category, description, id) values ('DDC', '470', 'Latein', -36)
insert into category (type, category, description, id) values ('DDC', '480', 'Griechisch', -37)
insert into category (type, category, description, id) values ('DDC', '490', 'Andere Sprachen', -38)
insert into category (type, category, description, id) values ('DDC', '491.8', 'Slawische Sprachen', -39)
insert into category (type, category, description, id) values ('DDC', '500', 'Naturwissenschaften', -40)
insert into category (type, category, description, id) values ('DDC', '510', 'Mathematik', -41)
insert into category (type, category, description, id) values ('DDC', '520', 'Astronomie, Kartografie', -42)
insert into category (type, category, description, id) values ('DDC', '530', 'Physik', -43)
insert into category (type, category, description, id) values ('DDC', '540', 'Chemie', -44)
insert into category (type, category, description, id) values ('DDC', '550', 'Geowissenschaften', -45)
insert into category (type, category, description, id) values ('DDC', '560', 'Paläontologie', -46)
insert into category (type, category, description, id) values ('DDC', '570', 'Biowissenschaften, Biologie', -47)
insert into category (type, category, description, id) values ('DDC', '580', 'Pflanzen (Botanik)', -48)
insert into category (type, category, description, id) values ('DDC', '590', 'Tiere (Zoologie)', -49)
insert into category (type, category, description, id) values ('DDC', '600', 'Technik', -50)
insert into category (type, category, description, id) values ('DDC', '610', 'Medizin, Gesundheit', -51)
insert into category (type, category, description, id) values ('DDC', '620', 'Ingenieurwissenschaften und Maschinenbau', -52)
insert into category (type, category, description, id) values ('DDC', '621.3', 'Elektrotechnik, Elektronik', -53)
insert into category (type, category, description, id) values ('DDC', '624', 'Ingenieurbau und Umwelttechnik', -54)
insert into category (type, category, description, id) values ('DDC', '630', 'Landwirtschaft, Veterinärmedizin', -55)
insert into category (type, category, description, id) values ('DDC', '640', 'Hauswirtschaft und Familienleben', -56)
insert into category (type, category, description, id) values ('DDC', '650', 'Management', -57)
insert into category (type, category, description, id) values ('DDC', '660', 'Technische Chemie', -58)
insert into category (type, category, description, id) values ('DDC', '670', 'Industrielle und handwerkliche Fertigung', -59)
insert into category (type, category, description, id) values ('DDC', '690', 'Hausbau, Bauhandwerk', -60)
insert into category (type, category, description, id) values ('DDC', '700', 'Künste, Bildende Kunst allgemein', -61)
insert into category (type, category, description, id) values ('DDC', '710', 'Landschaftsgestaltung, Raumplanung', -62)
insert into category (type, category, description, id) values ('DDC', '720', 'Architektur', -63)
insert into category (type, category, description, id) values ('DDC', '730', 'Plastik, Numismatik, Keramik, Metallkunst', -64)
insert into category (type, category, description, id) values ('DDC', '740', 'Grafik, angewandte Kunst', -65)
insert into category (type, category, description, id) values ('DDC', '741.5', 'Comics, Cartoons, Karikaturen', -66)
insert into category (type, category, description, id) values ('DDC', '750', 'Malerei', -67)
insert into category (type, category, description, id) values ('DDC', '760', 'Druckgrafik, Drucke', -68)
insert into category (type, category, description, id) values ('DDC', '770', 'Fotografie, Video, Computerkunst', -69)
insert into category (type, category, description, id) values ('DDC', '780', 'Musik', -70)
insert into category (type, category, description, id) values ('DDC', '790', 'Freizeitgestaltung, Darstellende Kunst', -71)
insert into category (type, category, description, id) values ('DDC', '791', 'Öffentliche Darbietungen, Film, Rundfunk', -72)
insert into category (type, category, description, id) values ('DDC', '792', 'Theater, Tanz', -73)
insert into category (type, category, description, id) values ('DDC', '793', 'Spiel', -74)
insert into category (type, category, description, id) values ('DDC', '796', 'Sport', -75)
insert into category (type, category, description, id) values ('DDC', '800', 'Literatur, Rhetorik, Literaturwissenschaft', -76)
insert into category (type, category, description, id) values ('DDC', '810', 'Englische Literatur Amerikas', -77)
insert into category (type, category, description, id) values ('DDC', '820', 'Englische Literatur', -78)
insert into category (type, category, description, id) values ('DDC', '830', 'Deutsche Literatur', -79)
insert into category (type, category, description, id) values ('DDC', '839', 'Literatur in anderen germanischen Sprachen', -80)
insert into category (type, category, description, id) values ('DDC', '840', 'Französische Literatur', -81)
insert into category (type, category, description, id) values ('DDC', '850', 'Italienische, rumänische, rätoromanische Literatur', -82)
insert into category (type, category, description, id) values ('DDC', '860', 'Spanische und portugiesische Literatur', -83)
insert into category (type, category, description, id) values ('DDC', '870', 'Lateinische Literatur', -84)
insert into category (type, category, description, id) values ('DDC', '880', 'Griechische Literatur', -85)
insert into category (type, category, description, id) values ('DDC', '890', 'Literatur in anderen Sprachen', -86)
insert into category (type, category, description, id) values ('DDC', '891.8', 'Slawische Literatur', -87)
insert into category (type, category, description, id) values ('DDC', '900', 'Geschichte', -88)
insert into category (type, category, description, id) values ('DDC', '910', 'Geografie, Reisen', -89)
insert into category (type, category, description, id) values ('DDC', '914.3', 'Geografie, Reisen (Deutschland)', -90)
insert into category (type, category, description, id) values ('DDC', '920', 'Biografie, Genealogie, Heraldik', -91)
insert into category (type, category, description, id) values ('DDC', '930', 'Alte Geschichte, Archäologie', -92)
insert into category (type, category, description, id) values ('DDC', '940', 'Geschichte Europas', -93)
insert into category (type, category, description, id) values ('DDC', '943', 'Geschichte Deutschlands', -94)
insert into category (type, category, description, id) values ('DDC', '950', 'Geschichte Asiens', -95)
insert into category (type, category, description, id) values ('DDC', '960', 'Geschichte Afrikas', -96)
insert into category (type, category, description, id) values ('DDC', '970', 'Geschichte Nordamerikas', -97)
insert into category (type, category, description, id) values ('DDC', '980', 'Geschichte Südamerikas', -98)
insert into category (type, category, description, id) values ('DDC', '990', 'Geschichte der übrigen Welt', -99)
insert into category (type, category, description, id) values ('DDC', 'B', 'Belletristik', -100)
insert into category (type, category, description, id) values ('DDC', 'K', 'Kinder- und Jugendliteratur', -101)
insert into category (type, category, description, id) values ('DDC', 'S', 'Schulbücher', -102)


insert into user_categories (user_id, category_id) values (-1, -51)
insert into user_categories (user_id, category_id) values (-1, -18)
insert into user_categories (user_id, category_id) values (-1, -100)
insert into user_categories (user_id, category_id) values (-1, -101)
insert into user_categories (user_id, category_id) values (-1, -102)
insert into user_categories (user_id, category_id) values (-1, -79)
